<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\book.ico" />
    <None Remove="Resources\book.png" />
    <None Remove="SampleBookData\covers\Alices-Adventures-in-Wonderland.jpg" />
    <None Remove="SampleBookData\covers\clean_code.jpg" />
    <None Remove="SampleBookData\covers\Hobbit.jpg" />
    <None Remove="SampleBookData\covers\Introduction-to-Modern-OpenGL.jpg" />
    <None Remove="SampleBookData\covers\Niedzwiedzi-Bog.jpg" />
    <None Remove="SampleBookData\covers\Quantum-Computing-for-the-Quantum-Curious.jpg" />
    <None Remove="SampleBookData\covers\Succeed-In-Software.jpg" />
    <None Remove="SampleBookData\covers\ukochane-rownanie-profesora.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SampleBookData\covers\Alices-Adventures-in-Wonderland.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleBookData\covers\clean_code.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleBookData\covers\Hobbit.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleBookData\covers\Introduction-to-Modern-OpenGL.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleBookData\covers\Niedzwiedzi-Bog.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleBookData\covers\Quantum-Computing-for-the-Quantum-Curious.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleBookData\covers\Succeed-In-Software.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SampleBookData\covers\ukochane-rownanie-profesora.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\book.ico" />
    <Resource Include="Resources\book.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <Folder Include="Controls\" />
    <Folder Include="Converters\" />
    <Folder Include="Services\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
